name: Selenium Automation Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  authenticate:
    name: Authenticate
    runs-on: ubuntu-latest
    container: eclipse-temurin:20-jdk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: apt-get update && apt-get install -y curl jq
      
      - name: Fetch Token
        run: bash fetch-token.sh
      
      - name: Save Token
        run: cat variables.sh > $GITHUB_ENV

  run_login_feature:
    name: Run Login Feature Tests
    runs-on: ubuntu-latest
    needs: authenticate
    container: eclipse-temurin:20-jdk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: apt-get update && apt-get install -y maven curl chromium chromium-driver
      
      - name: Load Token
        run: source variables.sh || { echo "❌ Token not found, exiting"; exit 1; }
      
      - name: Run Tests
        run: |
          export CHROME_BIN=/usr/bin/chromium
          echo "🧪 Running login.feature test with obtained token..."
          mvn clean test "-DsuiteXmlFile=testng.xml" "-DaccessToken=$ACCESS_TOKEN"
      
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/

  generate_report:
    name: Generate Report
    runs-on: ubuntu-latest
    needs: run_login_feature
    container: eclipse-temurin:20-jdk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: apt-get update && apt-get install -y curl jq maven
      
      - name: Debug Network Connectivity
        run: curl -v --connect-timeout 10 https://dev-keycloak.santechture.com
      
      - name: Generate HTML Report
        run: mvn exec:java "-Dexec.mainClass=utils.ReportGenerator"
      
      - name: Upload Report Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: enhanced-report
          path: target/enhanced-report/

